apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeploy-2
  namespace: segredosdesucesso 
  labels:
        app: meudeploy-2
        chaves: secretas
spec:
  selector:
    matchLabels:
      app: meudeploy-2
  template:
    metadata:
      labels:
        app: meudeploy-2
        chaves: secretas
    spec:
      containers:
      - name: meudeploy-2
        image: nginx:1.16
        resources:
          limits:
            memory: "28Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        env:
          - name: CHAVE_SECRETA
            valueFrom:
              secretKeyRef:
                name: meusegredo
                key: chave-secreta
          - name: SEGREDO
            valueFrom:
              secretKeyRef:
                name: meusegredo
                key: segredo