apiVersion: v1
kind: ServiceAccount
metadata:
  name: userx
  namespace: developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: developer
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # Pode ser usado ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role-binding
  namespace: developer
subjects:
- kind: ServiceAccount
  name: userx
  namespace: developer
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io